version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    environment:
      - MARIADB_USER=bn_reportserver
      - MARIADB_DATABASE=bitnami_reportserver
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  reportserverenterprise:
    image: docker.io/bitnami/reportserverenterprise:3
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - REPORTSERVER_DATABASE_USER=bn_reportserver
      - REPORTSERVER_DATABASE_NAME=bitnami_reportserver
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - TOMCAT_EXTRA_JAVA_OPTS=--add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/jdk.internal.ref=ALL-UNNAMED --add-opens=java.base/jdk.internal.reflect=ALL-UNNAMED -Djavax.net.ssl.trustStoreType=JKS -Drs.configdir=/opt/bitnami/reportserver/WEB-INF/classes
    ports:
      - '80:8080'
      - '443:8443'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
