# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  java:
    tty: true # Enables debugging capabilities when attached to this container.
    image: docker.io/bitnami/java:21
    command: ["tail", "-f", "/dev/null"] # To keep the container running
    ports:
      - 8080:8080
    volumes:
      - .:/app
