version: '2'

services:
  harbor-registry:
    image: docker.io/bitnami/harbor-registry:2
    ports:
      - 5000:5000
    volumes:
      - harbor-registry_data:/storage
      - ./config/registry/:/etc/registry/:ro

volumes:
  harbor-registry_data:
    driver: local
