# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

version: '2'

services:
  python:
    tty: true # Enables debugging capabilities when attached to this container.
    image: docker.io/bitnami/python:3.11
    ports:
      - 8000:8000
    volumes:
      - .:/app
