version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.1-ol-7'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  phpmyadmin:
    image: 'bitnami/phpmyadmin:4-ol-7'
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - mariadb
    volumes:
      - 'phpmyadmin_data:/bitnami'
volumes:
  mariadb_data:
    driver: local
  phpmyadmin_data:
    driver: local
