version: '2'
services:
  solr:
    image: docker.io/bitnami/solr:8
    environment:
      - SOLR_ENABLE_AUTHENTICATION=yes
    ports:
      - '8983:8983'
    volumes:
      - 'solr_data:/bitnami/solr'
volumes:
  solr_data:
    driver: local
