version: '2'

services:
  python:
    tty: true # Enables debugging capabilities when attached to this container.
    image: 'bitnami/python:3.7-ol-7'
    ports:
      - 8000:8000
    volumes:
      - .:/app
