version: '2'
services:
  elasticsearch:
    image: 'bitnami/elasticsearch:latest'
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - 'elasticsearch_data:/bitnami/elasticsearch'
volumes:
  elasticsearch_data:
    driver: local
