version: '2'

services:
  php:
    tty: true # Enables debugging capabilities when attached to this container.
    image: 'bitnami/php-fpm:7.3-prod'
    ports:
      - 9000:9000
    volumes:
      - .:/app
