version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  application:
    image: 'bitnami/owncloud:latest'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'owncloud_data:/bitnami/owncloud'
      - 'apache_data:/bitnami/apache'
      - 'php_data:/bitnami/php'
    depends_on:
      - mariadb
    environment:
      - OWNCLOUD_HOST=owncloud.example.com
volumes:
  mariadb_data:
    driver: local
  owncloud_data:
    driver: local
  apache_data:
    driver: local
  php_data:
    driver: local
