version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.1'
    environment:
      - MARIADB_USER=bn_owncloud
      - MARIADB_DATABASE=bitnami_owncloud
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  owncloud:
    image: 'bitnami/owncloud:10'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - OWNCLOUD_DATABASE_USER=bn_owncloud
      - OWNCLOUD_DATABASE_NAME=bitnami_owncloud
      - ALLOW_EMPTY_PASSWORD=yes
      # Host for accessing OwnCloud
      # note: this setting will only be applied on the first run
      # ref: https://github.com/bitnami/bitnami-docker-owncloud#configuration
      - OWNCLOUD_HOST=localhost
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'owncloud_data:/bitnami'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  owncloud_data:
    driver: local
