version: '2'

services:
  node:
    tty: true # Enables debugging capabilities when attached to this container.
    # Build action should be successful from any RHEL Host system running the Docker service with subscription managed registered
    # + info: https://access.redhat.com/solutions/253273
    build: .
    # command: sh -c 'npm install && npm start'
    ports:
      - 3000:3000
    volumes:
      - .:/app
