version: '2'

services:
  postgresql:
    image: bitnami/postgresql:10
    environment:
      - POSTGRESQL_DATABASE=myapp

  express:
    tty: true # Enables debugging capabilities when attached to this container.
    image: bitnami/express:4
    command: npm run development
    environment:
      - PORT=3000
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres@postgresql/myapp

      - SKIP_DB_WAIT=0
      - SKIP_DB_MIGRATION=0
      - SKIP_NPM_INSTALL=0
      - SKIP_BOWER_INSTALL=0
    depends_on:
      - postgresql
    ports:
      - 3000:3000
    volumes:
      - .:/app
