version: '2'

services:
  postgresql:
    image: docker.io/bitnami/postgresql:13
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'

volumes:
  postgresql_data:
    driver: local
