version: '2'

services:
  wildfly:
    # Build action should be successful from any RHEL Host system running the Docker service with subscription managed registered
    # + info: https://access.redhat.com/solutions/253273
    build: .
    labels:
      kompose.service.type: nodeport
    ports:
      - '8080:8080'
      - '9990:9990'
    volumes:
      - 'wildfly_data:/bitnami'
    environment:
      - WILDFLY_PASSWORD=password

volumes:
  wildfly_data:
    driver: local
