version: '2'

services:
  harbor-jobservice:
    image: bitnami/harbor-jobservice:1
    ports:
      - 80:8080
    environment:
      - CORE_SECRET=not-a-secure-core-secret
      - JOBSERVICE_SECRET=not-a-secure-jobservice-secret
      - CORE_URL=http://harbor-core:8080
    volumes:
      - harbor-jobservice_data:/var/log/jobs
      - ./config/jobservice/config.yml:/etc/jobservice/config.yml:ro

volumes:
  harbor-jobservice_data:
    driver: local
