version: '2'

services:
  harbor-clair:
    image: docker.io/bitnami/harbor-clair:1-debian-10
    ports:
      - '6060:6060'
      - '6061:6061'
    volumes:
      - harbor-clair_data:/bitnami
      - ./config/clair/config.yaml:/etc/clair/config.yaml:ro
  postgresql:
    image: docker.io/bitnami/postgresql:11-debian-10
    container_name: postgresql
    environment:
      - POSTGRESQL_PASSWORD=bitnami
    volumes:
      - postgresql_data:/bitnami/postgresql
volumes:
  harbor-clair_data:
    driver: local
  postgresql_data:
    driver: local
