version: '2'

services:
  grafana-image-renderer:
    image: docker.io/bitnami/grafana-image-renderer:3
    ports:
      - '8080:8080'
    environment:
      HTTP_HOST: "0.0.0.0"
      HTTP_PORT: "8080"
      ENABLE_METRICS: 'true'
