version: '2'
services:
  solr:
    # A Red Hat Customer Portal login is required to access this image. If you do not have one already, you can obtain one at https://www.redhat.com/wapps/ugc/register.html
    # Pull action should be successful from any RHEL Host system running the Docker service and executing the following command: docker login registry.connect.redhat.com
    # + info: https://access.redhat.com/containers/?tab=images&platform=docker#/registry.connect.redhat.com/bitnami/apache-solr
    image: registry.connect.redhat.com/bitnami/apache-solr
    ports:
      - '8983:8983'
    volumes:
      - 'solr_data:/bitnami'
volumes:
  solr_data:
    driver: local
