# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  neo4j:
    image: docker.io/bitnami/neo4j:5
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'
    volumes:
      - 'neo4j_data:/bitnami'
volumes:
  neo4j_data:
    driver: local
