version: '2'
services:
  dotnet:
    image: docker.io/bitnami/dotnet:3.1-debian-10
    command: ["tail", "-f", "/dev/null"] # To keep the container running
    volumes:
      - dotnet_data:/app
volumes:
  dotnet_data:
    driver: local
