# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'
services:
  dotnet:
    image: docker.io/bitnami/dotnet:8
    command: ["tail", "-f", "/dev/null"] # To keep the container running
    volumes:
      - dotnet_data:/app
volumes:
  dotnet_data:
    driver: local
