version: '2'
services:
  neo4j:
    image: 'bitnami/neo4j:4'
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'
    volumes:
      - 'neo4j_data:/bitnami'
volumes:
  neo4j_data:
    driver: local
