version: '2'
services:
  # [TEST]
  dotnet-sdk:
    image: docker.io/bitnami/dotnet-sdk:7
    command: ["tail", "-f", "/dev/null"] # To keep the container running
    volumes:
      - dotnet_data:/app
volumes:
  dotnet_data:
    driver: local
