version: '2'

services:
  nginx:
    image: 'bitnami/nginx:latest'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'nginx_data:/bitnami/nginx'

volumes:
  nginx_data:
    driver: local
