# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'
services:
  jupyter-base-notebook:
    image: docker.io/bitnami/jupyter-base-notebook:4
    command: ["tail", "-f", "/dev/null"]
    ports:
      - 8888:8888
