version: '2'

services:
  node:
    tty: true # Enables debugging capabilities when attached to this container.
    image: 'bitnami/node:12'
    # command: sh -c 'npm install && npm start'
    ports:
      - 3000:3000
    volumes:
      - .:/app
