version: '2'
services:
  # [TEST]
  dokuwiki:
    image: docker.io/bitnami/dokuwiki:20230404
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - 'dokuwiki_data:/bitnami/dokuwiki'
volumes:
  dokuwiki_data:
    driver: local
