version: '2'

services:
  cluster-autoscaler:
    image: docker.io/bitnami/cluster-autoscaler:1
    volumes:
      - cluster-autoscaler_data:/bitnami
volumes:
  cluster-autoscaler_data:
    driver: local
