version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  application:
    image: 'bitnami/prestashop:latest'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - 'prestashop_data:/bitnami/prestashop'
      - 'apache_data:/bitnami/apache'
      - 'php_data:/bitnami/php'
    depends_on:
      - mariadb
    environment:
      - PRESTASHOP_HOST=localhost
volumes:
  mariadb_data:
    driver: local
  prestashop_data:
    driver: local
  apache_data:
    driver: local
  php_data:
    driver: local
