version: '2'

services:
  redis-sentinel:
    image: bitnami/redis-sentinel:6.0
    volumes:
      - redis-sentinel_data:/bitnami
  redis:
    image: bitnami/redis:4.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis_data:/bitnami
volumes:
  redis-sentinel_data:
    driver: local
  redis_data:
    driver: local
