version: "2"
services:
  elasticsearch:
    image: "docker.io/bitnami/elasticsearch:6"
    volumes:
      - "elasticsearch_data:/bitnami"
  kibana:
    image: "docker.io/bitnami/kibana:6-debian-10"
    ports:
      - "5601:5601"
    volumes:
      - "kibana_data:/bitnami"
    depends_on:
      - elasticsearch
volumes:
  elasticsearch_data:
    driver: local
  kibana_data:
    driver: local
