version: '2'
services:
  dokuwiki:
    image: 'docker.io/bitnami/dokuwiki:20200729-debian-10'
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - 'dokuwiki_data:/bitnami/dokuwiki'
volumes:
  dokuwiki_data:
    driver: local
