# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'

services:
  contour:
    image: docker.io/bitnami/contour:1.27
    volumes:
      - contour_data:/bitnami/contour
volumes:
  contour_data:
    driver: local
