# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  php:
    tty: true # Enables debugging capabilities when attached to this container.
    image: docker.io/bitnami/php:8.4
    ports:
      - 9000:9000
    volumes:
      - .:/app
