# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

version: '2'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:14
    volumes:
      - postgresql_data:/bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=kong
      - POSTGRESQL_PASSWORD=bitnami
      - POSTGRESQL_DATABASE=kong
  kong:
    image: docker.io/bitnami/kong:3
    ports:
      - 8000:8000
      - 8443:8443
    environment:
      - KONG_MIGRATE=yes
      - KONG_PG_HOST=postgresql
      - KONG_PG_PASSWORD=bitnami
volumes:
  postgresql_data:
    driver: local
