# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  tomcat:
    image: docker.io/bitnami/tomcat:10.1
    ports:
      - '8080:8080'
    volumes:
      - 'tomcat_data:/bitnami/tomcat'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  tomcat_data:
    driver: local
