version: '2'
services:
  application:
    image: 'bitnami/jenkins:latest'
    ports:
      - '80:8080'
      - '443:8443'
      - '50000:50000'
    volumes:
      - 'jenkins_data:/bitnami/jenkins'
volumes:
  jenkins_data:
    driver: local
