version: '2'

services:
  postgresql:
    image: 'bitnami/postgresql:9.6'
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami'

volumes:
  postgresql_data:
    driver: local
