version: '2'

services:
  jruby:
    tty: true # Enables debugging capabilities when attached to this container.
    image: docker.io/bitnami/jruby:9.2-debian-10
    # command: sh -c 'bundle install && bundle exec rails server -b 0.0.0.0 -p 3000'
    ports:
      - 3000:3000
    volumes:
      - .:/app
