version: '2'

services:
  opensearch:
    image: docker.io/bitnami/opensearch:2
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - 'opensearch_data:/bitnami/opensearch/data'
volumes:
  opensearch_data:
    driver: local
