# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  clickhouse-keeper:
    image: docker.io/bitnami/clickhouse-keeper:26
    environment:
      - CLICKHOUSE_KEEPER_SERVER_ID=1
    ports:
      - '9181:9181'
      - '9234:9234'
    volumes:
      - clickhouse_keeper_data:/bitnami/clickhouse-keeper
volumes:
  clickhouse_keeper_data:
    driver: local
