version: '2'

services:
  minio:
    image: 'bitnami/minio:2020'
    ports:
      - 9000:9000
    volumes:
      - 'minio_data:/data'
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=miniosecret
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minio,minio2,minio3,minio4
  minio2:
    image: 'bitnami/minio:2020'
    volumes:
      - 'minio_2_data:/data'
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=miniosecret
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minio,minio2,minio3,minio4
  minio3:
    image: 'bitnami/minio:2020'
    volumes:
      - 'minio_3_data:/data'
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=miniosecret
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minio,minio2,minio3,minio4
  minio4:
    image: 'bitnami/minio:2020'
    volumes:
      - 'minio_4_data:/data'
    environment:
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=miniosecret
      - MINIO_DISTRIBUTED_MODE_ENABLED=yes
      - MINIO_DISTRIBUTED_NODES=minio,minio2,minio3,minio4

volumes:
  minio_data:
    driver: local
  minio_2_data:
    driver: local
  minio_3_data:
    driver: local
  minio_4_data:
    driver: local
