version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  phpmyadmin:
    image: 'bitnami/phpmyadmin:4'
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - mariadb
    volumes:
      - 'apache_data:/bitnami/apache'
      - 'php_data:/bitnami/php'
      - 'phpmyadmin_data:/bitnami/phpmyadmin'
volumes:
  mariadb_data:
    driver: local
  apache_data:
    driver: local
  php_data:
    driver: local
  phpmyadmin_data:
    driver: local
