version: '2'

services:
  fluentd:
    image: bitnami/fluentd:1
    ports:
      - '24224:24224'
      - '5140:5140'
    volumes:
      - fluentd_data:/bitnami/fluentd
volumes:
  fluentd_data:
    driver: local
