version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.3
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
  myapp:
    image: docker.io/bitnami/rails:7
    ports:
      - '3000:3000'
    environment:
      - DATABASE_HOST=mariadb
      - DATABASE_NAME=my_app_development
    volumes:
      - './my-project:/app'
    depends_on:
      - mariadb
