version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  orangehrm:
    image: 'bitnami/orangehrm:3'
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - mariadb
    volumes:
      - 'orangehrm_data:/bitnami/orangehrm'
      - 'apache_data:/bitnami/apache'
      - 'php_data:/bitnami/php'

volumes:
  mariadb_data:
    driver: local
  orangehrm_data:
    driver: local
  apache_data:
    driver: local
  php_data:
    driver: local
