version: '2'

services:
  spring-cloud-skipper:
    image: docker.io/bitnami/spring-cloud-skipper:2
    restart: always
    environment:
      - SERVER_PORT=7577
      - SPRING_CLOUD_SKIPPER_SERVER_PLATFORM_LOCAL_ACCOUNTS_DEFAULT_PORTRANGE_LOW=20000
      - SPRING_CLOUD_SKIPPER_SERVER_PLATFORM_LOCAL_ACCOUNTS_DEFAULT_PORTRANGE_HIGH=20100
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/skipper?useMysqlMetadata=true
      - SPRING_DATASOURCE_USERNAME=bn_skipper
      - SPRING_DATASOURCE_PASSWORD=bn_skipper
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.mariadb.jdbc.Driver
    ports:
      - '7577:7577'
    depends_on:
      - mariadb
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    environment:
      - MARIADB_ROOT_PASSWORD=root_password
      - MARIADB_USER=bn_skipper
      - MARIADB_PASSWORD=bn_skipper
      - MARIADB_DATABASE=skipper
    volumes:
      - 'mariadb_data:/bitnami'
volumes:
  mariadb_data:
    driver: local
  zookeeper_data:
    driver: local
