version: '2'

services:
  harbor-registryctl:
    image: bitnami/harbor-registryctl:1
    ports:
      - 80:8080
    environment:
      - CORE_SECRET=not-a-secure-core-secret
      - JOBSERVICE_SECRET=not-a-secure-jobservice-secret
    volumes:
      - harbor-registry_data:/storage
      - ./config/registry/:/etc/registry/:ro
      - ./config/registryctl/config.yml:/etc/registryctl/config.yml:ro

volumes:
  harbor-registry_data:
    driver: local
