# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'
services:
  jupyterhub:
    image: docker.io/bitnami/jupyterhub:4
    entrypoint: ["tail", "-f", "/dev/null"]
    ports:
      - 8081:8081
