version: '2'

services:
  elasticsearch:
    image: 'bitnami/elasticsearch:5'
    ports:
      - '9200:9200'
      - '9300:9300'
    volumes:
      - 'elasticsearch_data:/bitnami'
volumes:
  elasticsearch_data:
    driver: local
