# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:11.3
    environment:
      - MARIADB_ROOT_PASSWORD=bitnami
    volumes:
      - 'mariadb_data:/bitnami'
  phpmyadmin:
    image: docker.io/bitnami/phpmyadmin:5
    ports:
      - '80:8080'
      - '443:8443'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
