version: '2'

services:
  mariadb-galera:
    image: 'bitnami/mariadb-galera:10.3'
    ports:
      - '3306:3306'
      - '4444:4444'
      - '4567:4567'
      - '4568:4568'
    volumes:
      - 'mariadb_galera_data:/bitnami/mariadb'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  mariadb_galera_data:
    driver: local
