version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  jasperreports:
    image: 'bitnami/jasperreports:latest'
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - 'jasperreports_data:/bitnami/jasperreports'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  jasperreports_data:
    driver: local
