# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  logstash:
    image: docker.io/bitnami/logstash:9.1
    ports:
      - 8080:8080
    volumes:
      - logstash_data:/bitnami
volumes:
  logstash_data:
    driver: local
