# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

version: '2.1'
services:
  postgresql:
    image: docker.io/bitnami/postgresql:14
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_PASSWORD=bitnami123

  pgbouncer:
    image: docker.io/bitnami/pgbouncer:1
    ports:
      - 6432:6432
    environment:
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_PASSWORD=bitnami123
volumes:
  postgresql_data:
    driver: local
