version: '2'

services:
  php:
    tty: true # Enables debugging capabilities when attached to this container.
    image: docker.io/bitnami/php-fpm:8.2
    ports:
      - 9000:9000
    volumes:
      - .:/app
