version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami'
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'redis_data:/bitnami'
  mongodb:
    image: 'bitnami/mongodb:latest'
    volumes:
      - 'mongodb_data:/bitnami'
  dreamfactory:
    image: 'bitnami/dreamfactory:latest'
    labels:
      kompose.service.type: nodeport
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - mariadb
      - redis
      - mongodb
    volumes:
      - 'dreamfactory_data:/bitnami'
volumes:
  mariadb_data:
    driver: local
  redis_data:
    driver: local
  mongodb_data:
    driver: local
  dreamfactory_data:
    driver: local
