version: '2'
services:
  elasticsearch:
    image: 'bitnami/elasticsearch:latest'
    volumes:
      - 'elasticsearch_data:/bitnami'
  kibana:
    image: 'bitnami/kibana:5'
    labels:
      kompose.service.type: nodeport
    ports:
      - '5601:5601'
    volumes:
      - 'kibana_data:/bitnami'
    depends_on:
      - elasticsearch
volumes:
  elasticsearch_data:
    driver: local
  kibana_data:
    driver: local
