# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

gossfile:
  # Goss tests exclusive to the current container
  ../../alertmanager/goss/alertmanager.yaml: { }
  # Load scripts from .vib/common/goss/templates
  ../../common/goss/templates/check-app-version.yaml: {}
  ../../common/goss/templates/check-binaries.yaml: {}
  ../../common/goss/templates/check-broken-symlinks.yaml: {}
  ../../common/goss/templates/check-ca-certs.yaml: {}
  ../../common/goss/templates/check-linked-libraries.yaml: {}
  ../../common/goss/templates/check-sed-in-place.yaml: {}
  ../../common/goss/templates/check-spdx.yaml: {}
