version: '2'

services:
  postgresql:
    image: 'bitnami/postgresql:11'
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami'
    environment:
      - 'ALLOW_EMPTY_PASSWORD=yes'

volumes:
  postgresql_data:
    driver: local
