version: '2'

services:
  mongodb:
    image: docker.io/bitnami/mongodb:4.2
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  express:
    tty: true # Enables debugging capabilities when attached to this container.
    image: docker.io/bitnami/express:4
    command: npm start
    environment:
      - PORT=3000
      - NODE_ENV=development
      - DATABASE_URL=mongodb://mongodb:27017/myapp

      - SKIP_DB_WAIT=0
      - SKIP_DB_MIGRATION=0
      - SKIP_NPM_INSTALL=0
      - SKIP_BOWER_INSTALL=0
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    volumes:
      - .:/app
