name: Sync containers repositories

on:
  schedule:
    # Every day at 1 AM
    - cron: '0 1 * * *'
  workflow_dispatch:
    inputs:
      shift:
        description: 'Commits to shift if you edited the containers folder'     
        default: '0'
jobs:
  build:
    name: Trigger Site Rebuild
    runs-on: ubuntu-latest
    steps:
      - name: Checkout bitnami/containers
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BITNAMI_BOT_SECRET }}
          fetch-depth: 0
      - name: Fetch
        run: ./scripts/fetch-commits.sh ${{ github.event.inputs.shift }} 
