version: '2'
services:
  mongodb:
    image: 'docker.io/bitnami/mongodb:4.2-debian-10'
    volumes:
      - 'mongodb_data:/bitnami'
  parse:
    image: 'docker.io/bitnami/parse:4-debian-10'
    ports:
      - '1337:1337'
    volumes:
      - 'parse_data:/bitnami'
    depends_on:
      - mongodb
volumes:
  mongodb_data:
    driver: local
  parse_data:
    driver: local
