version: '2'
services:
  harbor-adapter-trivy:
    image: docker.io/bitnami/harbor-adapter-trivy:1-debian-10
    ports:
      - 8080:8080
    volumes:
      - harbor-adapter-trivy_data:/bitnami
volumes:
  harbor-adapter-trivy_data:
    driver: local
